// src/Labtest/labTests.js

const labTests = [
  {
    id: 1,
    name: "Complete Blood Count (CBC)",
    price: 250,
    discount: 20,
    category: "Blood Tests",
    description: "Measures overall health and detects disorders like anemia.",
  },
  {
    id: 2,
    name: "Thyroid Profile",
    price: 500,
    discount: 15,
    category: "Hormone Tests",
    description: "Assesses thyroid function for hypothyroidism or hyperthyroidism.",
  },
  {
    id: 3,
    name: "Liver Function Test (LFT)",
    price: 700,
    discount: 10,
    category: "Organ Function",
    description: "Checks liver health by analyzing enzyme and protein levels.",
  },
  {
    id: 4,
    name: "Diabetes Screening",
    price: 350,
    discount: 25,
    category: "Diabetes",
    description: "Evaluates blood sugar levels to detect diabetes.",
  },
  {
    id: 5,
    name: "Cardiac Risk Markers",
    price: 1200,
    discount: 30,
    category: "Heart Tests",
    description: "Assesses risk for heart diseases through biomarkers.",
  },
  {
    id: 6,
    name: "Vitamin D Test",
    price: 600,
    discount: 10,
    category: "Vitamin Tests",
    description: "Measures the level of Vitamin D to ensure bone and immune health.",
  },
  {
    id: 7,
    name: "Kidney Function Test (KFT)",
    price: 650,
    discount: 15,
    category: "Organ Function",
    description: "Assesses kidney health by analyzing creatinine and urea levels.",
  },
  {
    id: 8,
    name: "Iron Studies",
    price: 400,
    discount: 5,
    category: "Blood Tests",
    description: "Evaluates iron levels to detect anemia or iron deficiency.",
  },
  {
    id: 9,
    name: "Lipid Profile",
    price: 500,
    discount: 20,
    category: "Heart Tests",
    description: "Measures cholesterol and triglycerides to assess heart health.",
  },
  {
    id: 10,
    name: "HbA1c Test",
    price: 450,
    discount: 10,
    category: "Diabetes",
    description: "Checks average blood sugar levels over the past 2-3 months.",
  },
  {
    id: 11,
    name: "Vitamin B12 Test",
    price: 550,
    discount: 12,
    category: "Vitamin Tests",
    description: "Determines Vitamin B12 levels to prevent anemia and nerve disorders.",
  },
  {
    id: 12,
    name: "Prostate-Specific Antigen (PSA)",
    price: 800,
    discount: 15,
    category: "Cancer Screening",
    description: "Screens for prostate abnormalities in men.",
  },
  {
    id: 13,
    name: "Pap Smear Test",
    price: 700,
    discount: 20,
    category: "Cancer Screening",
    description: "Detects cervical cancer and other abnormal cells in women.",
  },
  {
    id: 14,
    name: "C-Reactive Protein (CRP)",
    price: 350,
    discount: 10,
    category: "Inflammation Markers",
    description: "Identifies inflammation in the body and monitors chronic diseases.",
  },
  {
    id: 15,
    name: "Urine Routine Test",
    price: 200,
    discount: 5,
    category: "Urine Tests",
    description: "Checks urine composition to detect infections or kidney disorders.",
  },
  {
    id: 16,
    name: "Electrolyte Panel",
    price: 550,
    discount: 15,
    category: "Blood Tests",
    description: "Measures essential electrolytes for hydration and organ function.",
  },
  {
    id: 17,
    name: "Chest X-Ray",
    price: 700,
    discount: 20,
    category: "Imaging Tests",
    description: "Provides images of the chest to diagnose lung or heart conditions.",
  },
  {
    id: 18,
    name: "Ultrasound Abdomen",
    price: 1200,
    discount: 25,
    category: "Imaging Tests",
    description: "Evaluates organs in the abdomen for abnormalities or diseases.",
  },
  {
    id: 19,
    name: "Allergy Panel",
    price: 1500,
    discount: 30,
    category: "Immunology",
    description: "Identifies allergic reactions to various environmental or food allergens.",
  },
  {
    id: 20,
    name: "Thyroid Antibodies Test",
    price: 650,
    discount: 12,
    category: "Hormone Tests",
    description: "Detects autoimmune thyroid disorders like Hashimoto's disease.",
  },
  {
    id: 21,
    name: "Electrocardiogram (ECG)",
    price: 400,
    discount: 10,
    category: "Heart Tests",
    description: "Records the heart's electrical activity to identify cardiac issues.",
  },
  {
    id: 22,
    name: "Bone Density Test (DEXA Scan)",
    price: 1800,
    discount: 20,
    category: "Bone Health",
    description: "Measures bone strength to assess risk of osteoporosis.",
  },
  {
    id: 23,
    name: "Hepatitis B Surface Antigen (HBsAg)",
    price: 600,
    discount: 15,
    category: "Infectious Disease",
    description: "Screens for Hepatitis B infection in the body.",
  },
  {
    id: 24,
    name: "HIV Screening Test",
    price: 500,
    discount: 10,
    category: "Infectious Disease",
    description: "Detects HIV infection early for timely treatment.",
  },
  {
    id: 25,
    name: "Stool Routine Test",
    price: 300,
    discount: 5,
    category: "Digestive Health",
    description: "Analyzes stool to detect infections or digestive issues.",
  }
];

export default labTests;
