import vitaminC from "../assets/vitaminC.jpg";
import diabeticGlucometer from "../assets/diabeticGlucometer.jpg";
import cream from "../assets/cream.jpg";
import facewash from "../assets/facewash.jpg";
import zincovit from "../assets/zincovit.jpg";
import proteinPowder from "../assets/proteinPowder.jpg";
import ashwagandha from "../assets/ashwagandha.jpg";
import ironFolic from "../assets/ironFolic.jpg";
import biotin from "../assets/biotin.jpg";
import spirulina from "../assets/spirulina.jpg";
import accuChek from "../assets/accuChek.jpg";
import contourPlus from "../assets/contourPlus.jpg";
import testStrips from "../assets/testStrips.jpg";
import glucoone from "../assets/glucoone.jpg";
import sugarfreeGold from "../assets/sugarfreeGold.jpg";
import diabecon from "../assets/diabecon.jpg";
import dProtein from "../assets/dProtein.jpg";
import diabeticJuice from "../assets/diabeticJuice.jpeg";
import Hfacewash from "../assets/Hfacewash.jpg";
import niveaCream from "../assets/niveaCream.jpg";
import mamaearthMask from "../assets/mamaearthMask.jpg";
import cetaphilCleanser from "../assets/cetaphilCleanser.jpg";
import pondsSerum from "../assets/pondsSerum.jpg";
import lorealNightcream from "../assets/lorealNightcream.jpg";
import neutrogenaSunscreen from "../assets/neutrogenaSunscreen.jpg";
import dermacoVitc from "../assets/dermacoVitc.jpg";
import vaselineLotion from "../assets/vaselineLotion.jpg";
import biotiquePack from "../assets/biotiquePack.jpg";
import magnesiumB6 from "../assets/magnesiumB6.jpg";
import vitaminD3 from "../assets/vitaminD3.jpg";
import probiotic from "../assets/probiotic.jpg";
import collagen from "../assets/collagen.jpg";

const healthcareProducts = [
  {
    id: 41,
    name: "Vitamin C 500mg Tablet",
    category: "Supplements",
    price: 299,
    discount: 20,
    stock: true,
    rating: 4.5,
    image: vitaminC,
  },
  {
    id: 42,
    name: "Diabetic Care Glucometer",
    category: "Diabetic Care",
    price: 1200,
    discount: 15,
    stock: true,
    rating: 4.8,
    image: diabeticGlucometer,
  },
  {
    id: 43,
    name: "Moisturizing Cream",
    category: "Skin Care",
    price: 450,
    discount: 0,
    stock: true,
    rating: 4.2,
    image: cream,
  },
  {
    id: 44,
    name: "Herbal Face Wash",
    category: "Skin Care",
    price: 250,
    discount: 10,
    stock: true,
    rating: 4.0,
    image: facewash,
  },
  {
    id: 45,
    name: "Zincovit Multivitamin Tablets",
    category: "Supplements",
    price: 220,
    discount: 5,
    stock: true,
    rating: 4.4,
    image: zincovit,
  },
  {
    id: 46,
    name: "Protein Powder (Vanilla Flavor)",
    category: "Supplements",
    price: 1250,
    discount: 18,
    stock: true,
    rating: 4.9,
    image: proteinPowder,
  },
  {
    id: 47,
    name: "Ashwagandha Capsules",
    category: "Supplements",
    price: 299,
    discount: 20,
    stock: true,
    rating: 4.6,
    image: ashwagandha,
  },
  {
    id: 48,
    name: "Iron + Folic Acid Tablets",
    category: "Supplements",
    price: 180,
    discount: 10,
    stock: true,
    rating: 4.3,
    image: ironFolic,
  },
  {
    id: 49,
    name: "Biotin Hair & Skin Capsules",
    category: "Supplements",
    price: 499,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: biotin,
  },
  {
    id: 50,
    name: "Spirulina Tablets",
    category: "Supplements",
    price: 350,
    discount: 12,
    stock: true,
    rating: 4.5,
    image: spirulina,
  },
  {
    id: 51,
    name: "Accu-Chek Active Glucometer",
    category: "Diabetic Care",
    price: 1199,
    discount: 15,
    stock: true,
    rating: 4.8,
    image: accuChek,
  },
  {
    id: 52,
    name: "Contour Plus One Blood Glucose Monitor",
    category: "Diabetic Care",
    price: 1299,
    discount: 10,
    stock: true,
    rating: 4.7,
    image: contourPlus,
  },
  {
    id: 53,
    name: "Accu-Chek Instant Test Strips (50 Strips)",
    category: "Diabetic Care",
    price: 899,
    discount: 12,
    stock: true,
    rating: 4.6,
    image: testStrips,
  },
  {
    id: 54,
    name: "Dr. Morepen Gluco One BG-03 Glucometer",
    category: "Diabetic Care",
    price: 999,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: glucoone,
  },
  {
    id: 55,
    name: "Sugar-Free Gold Low-Calorie Sweetener (500 Pellets)",
    category: "Diabetic Care",
    price: 195,
    discount: 8,
    stock: true,
    rating: 4.4,
    image: sugarfreeGold,
  },
  {
    id: 56,
    name: "Himalaya Diabecon Tablets (60 Tabs)",
    category: "Diabetic Care",
    price: 220,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: diabecon,
  },
  {
    id: 57,
    name: "D-Protein Nutritional Powder (Chocolate Flavour)",
    category: "Diabetic Care",
    price: 640,
    discount: 12,
    stock: true,
    rating: 4.6,
    image: dProtein,
  },
  {
    id: 58,
    name: "Herbal Diabetic Care Juice (Aloe Vera + Karela + Jamun)",
    category: "Diabetic Care",
    price: 299,
    discount: 10,
    stock: true,
    rating: 4.3,
    image: diabeticJuice,
  },
  {
    id: 59,
    name: "Himalaya Herbal Face Wash",
    category: "Skin Care",
    price: 250,
    discount: 10,
    stock: true,
    rating: 4.4,
    image: Hfacewash,
  },
  {
    id: 60,
    name: "Nivea Soft Moisturizing Cream",
    category: "Skin Care",
    price: 299,
    discount: 5,
    stock: true,
    rating: 4.6,
    image: niveaCream,
  },
  {
    id: 61,
    name: "Cetaphil Gentle Skin Cleanser",
    category: "Skin Care",
    price: 550,
    discount: 8,
    stock: true,
    rating: 4.8,
    image: cetaphilCleanser,
  },
  {
    id: 62,
    name: "Neutrogena Sunscreen SPF 50+",
    category: "Skin Care",
    price: 699,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: neutrogenaSunscreen,
  },
  {
    id: 63,
    name: "Mamaearth Ubtan Face Mask",
    category: "Skin Care",
    price: 499,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: mamaearthMask,
  },
  {
    id: 64,
    name: "Pond’s Bright Beauty Serum",
    category: "Skin Care",
    price: 399,
    discount: 12,
    stock: true,
    rating: 4.4,
    image: pondsSerum,
  },
  {
    id: 65,
    name: "L’Oréal Paris Night Cream",
    category: "Skin Care",
    price: 799,
    discount: 10,
    stock: true,
    rating: 4.6,
    image: lorealNightcream,
  },
  {
    id: 66,
    name: "The Derma Co. Vitamin C Face Serum",
    category: "Skin Care",
    price: 649,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: dermacoVitc,
  },
  {
    id: 67,
    name: "Vaseline Deep Restore Body Lotion",
    category: "Skin Care",
    price: 375,
    discount: 8,
    stock: true,
    rating: 4.5,
    image: vaselineLotion,
  },
  {
    id: 68,
    name: "Biotique Bio Fruit Whitening Face Pack",
    category: "Skin Care",
    price: 220,
    discount: 10,
    stock: true,
    rating: 4.3,
    image: biotiquePack,
  },
  {
    id: 69,
    name: "Magnesium + Vitamin B6 Tablets",
    category: "Supplements",
    price: 399,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: magnesiumB6,
  },
  {
    id: 70,
    name: "Vitamin D3 1000 IU Softgels",
    category: "Supplements",
    price: 349,
    discount: 12,
    stock: true,
    rating: 4.6,
    image: vitaminD3,
  },
  {
    id: 71,
    name: "Probiotic Capsules 30 Billion CFU",
    category: "Supplements",
    price: 599,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: probiotic,
  },
  {
    id: 72,
    name: "Collagen Peptides Powder",
    category: "Supplements",
    price: 1200,
    discount: 18,
    stock: true,
    rating: 4.8,
    image: collagen,
  }
];

export default healthcareProducts;
