// src/HealthcareProducts/healthcareData.js

const healthcareProducts = [
  {
    id: 1,
    name: "Vitamin C 500mg Tablet",
    category: "Supplements",
    price: 299,
    discount: 20,
    stock: true,
    rating: 4.5,
    image: "/Images/vitamin-c.jpg",
  },
  {
    id: 2,
    name: "Diabetic Care Glucometer",
    category: "Diabetic Care",
    price: 1200,
    discount: 15,
    stock: true,
    rating: 4.8,
    image: "/Images/glucometer.jpg",
  },
  {
    id: 3,
    name: "Moisturizing Cream",
    category: "Skin Care",
    price: 450,
    discount: 0,
    stock: true,
    rating: 4.2,
    image: "/Images/cream.jpg",
  },
  {
    id: 4,
    name: "Herbal Face Wash",
    category: "Skin Care",
    price: 250,
    discount: 10,
    stock: true,
    rating: 4.0,
    image: "/Images/facewash.jpg",
  },
  {
    id: 5,
    name: "Zincovit Multivitamin Tablets",
    category: "Supplements",
    price: 220,
    discount: 5,
    stock: true,
    rating: 4.4,
    image: "/Images/zincovit.jpg",
  },
  {
    id: 6,
    name: "Protein Powder (Vanilla Flavor)",
    category: "Supplements",
    price: 1250,
    discount: 18,
    stock: true,
    rating: 4.9,
    image: "/Images/protein-powder.jpg",
  },
  {
    id: 7,
    name: "Ashwagandha Capsules",
    category: "Supplements",
    price: 299,
    discount: 20,
    stock: true,
    rating: 4.6,
    image: "/Images/ashwagandha.jpg",
  },
  {
    id: 8,
    name: "Iron + Folic Acid Tablets",
    category: "Supplements",
    price: 180,
    discount: 10,
    stock: true,
    rating: 4.3,
    image: "/Images/iron-folic.jpg",
  },
  {
    id: 9,
    name: "Biotin Hair & Skin Capsules",
    category: "Supplements",
    price: 499,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: "/Images/biotin.jpg",
  },
  {
    id: 10,
    name: "Spirulina Tablets",
    category: "Supplements",
    price: 350,
    discount: 12,
    stock: true,
    rating: 4.5,
    image: "/Images/spirulina.jpg",
  },
  {
    id: 11,
    name: "Accu-Chek Active Glucometer",
    category: "Diabetic Care",
    price: 1199,
    discount: 15,
    stock: true,
    rating: 4.8,
    image: "/Images/accu-chek.jpg",
  },
  {
    id: 12,
    name: "Contour Plus One Blood Glucose Monitor",
    category: "Diabetic Care",
    price: 1299,
    discount: 10,
    stock: true,
    rating: 4.7,
    image: "/Images/contour-plus.jpg",
  },
  {
    id: 13,
    name: "Accu-Chek Instant Test Strips (50 Strips)",
    category: "Diabetic Care",
    price: 899,
    discount: 12,
    stock: true,
    rating: 4.6,
    image: "/Images/test-strips.jpg",
  },
  {
    id: 14,
    name: "Dr. Morepen Gluco One BG-03 Glucometer",
    category: "Diabetic Care",
    price: 999,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: "/Images/morepen-glucoone.jpg",
  },
  {
    id: 15,
    name: "Sugar-Free Gold Low-Calorie Sweetener (500 Pellets)",
    category: "Diabetic Care",
    price: 195,
    discount: 8,
    stock: true,
    rating: 4.4,
    image: "/Images/sugarfree-gold.jpg",
  },
  {
    id: 16,
    name: "Himalaya Diabecon Tablets (60 Tabs)",
    category: "Diabetic Care",
    price: 220,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: "/Images/diabecon.jpg",
  },
  {
    id: 17,
    name: "D-Protein Nutritional Powder (Chocolate Flavour)",
    category: "Diabetic Care",
    price: 640,
    discount: 12,
    stock: true,
    rating: 4.6,
    image: "/Images/d-protein.jpg",
  },
  {
    id: 18,
    name: "Herbal Diabetic Care Juice (Aloe Vera + Karela + Jamun)",
    category: "Diabetic Care",
    price: 299,
    discount: 10,
    stock: true,
    rating: 4.3,
    image: "/Images/diabetic-juice.jpg",
  },
  {
    id: 19,
    name: "Himalaya Herbal Face Wash",
    category: "Skin Care",
    price: 250,
    discount: 10,
    stock: true,
    rating: 4.4,
    image: "/Images/facewash.jpg",
  },
  {
    id: 20,
    name: "Nivea Soft Moisturizing Cream",
    category: "Skin Care",
    price: 299,
    discount: 5,
    stock: true,
    rating: 4.6,
    image: "/Images/nivea-cream.jpg",
  },
  {
    id: 21,
    name: "Cetaphil Gentle Skin Cleanser",
    category: "Skin Care",
    price: 550,
    discount: 8,
    stock: true,
    rating: 4.8,
    image: "/Images/cetaphil-cleanser.jpg",
  },
  {
    id: 22,
    name: "Neutrogena Sunscreen SPF 50+",
    category: "Skin Care",
    price: 699,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: "/Images/neutrogena-sunscreen.jpg",
  },
  {
    id: 23,
    name: "Mamaearth Ubtan Face Mask",
    category: "Skin Care",
    price: 499,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: "/Images/mamaearth-mask.jpg",
  },
  {
    id: 24,
    name: "Pond’s Bright Beauty Serum",
    category: "Skin Care",
    price: 399,
    discount: 12,
    stock: true,
    rating: 4.4,
    image: "/Images/ponds-serum.jpg",
  },
  {
    id: 25,
    name: "L’Oréal Paris Night Cream",
    category: "Skin Care",
    price: 799,
    discount: 10,
    stock: true,
    rating: 4.6,
    image: "/Images/loreal-nightcream.jpg",
  },
  {
    id: 26,
    name: "The Derma Co. Vitamin C Face Serum",
    category: "Skin Care",
    price: 649,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: "/Images/dermaco-vitc.jpg",
  },
  {
    id: 27,
    name: "Vaseline Deep Restore Body Lotion",
    category: "Skin Care",
    price: 375,
    discount: 8,
    stock: true,
    rating: 4.5,
    image: "/Images/vaseline-lotion.jpg",
  },
  {
    id: 28,
    name: "Biotique Bio Fruit Whitening Face Pack",
    category: "Skin Care",
    price: 220,
    discount: 10,
    stock: true,
    rating: 4.3,
    image: "/Images/biotique-pack.jpg",
  },
  {
    id: 29,
    name: "Magnesium + Vitamin B6 Tablets",
    category: "Supplements",
    price: 399,
    discount: 10,
    stock: true,
    rating: 4.5,
    image: "/Images/magnesium-b6.jpg",
  },
  {
    id: 30,
    name: "Vitamin D3 1000 IU Softgels",
    category: "Supplements",
    price: 349,
    discount: 12,
    stock: true,
    rating: 4.6,
    image: "/Images/vitamin-d3.jpg",
  },
  {
    id: 31,
    name: "Probiotic Capsules 30 Billion CFU",
    category: "Supplements",
    price: 599,
    discount: 15,
    stock: true,
    rating: 4.7,
    image: "/Images/probiotic.jpg",
  },
  {
    id: 32,
    name: "Collagen Peptides Powder",
    category: "Supplements",
    price: 1200,
    discount: 18,
    stock: true,
    rating: 4.8,
    image: "/Images/collagen.jpg",
  },
  {
    id: 33,
    name: "Green Tea Extract Capsules",
    category: "Supplements",
    price: 450,
    discount: 10,
    stock: true,
    rating: 4.4,
    image: "/Images/green-tea.jpg",
  },
];

export default healthcareProducts;
